source 'https://rubygems.org'

gem 'chef'
gem 'net-ssh-multi', '1.1.0'
gem 'berkshelf'
gem 'chefspec', git: 'https://github.com/acrmp/chefspec'
gem 'foodcritic'
gem 'rake'
gem 'right_aws'
gem 'strainer'
gem 'guard'
gem 'guard-strainer'
gem 'pry'
gem 'pry-debugger'
gem 'pry-remote'
gem 'knife-solo_data_bag'
gem 'coveralls', require: false
